version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todo-mysql-db
    restart: always
    env_file:
      - C:/Secrets/todo_app/.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - todo-db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER_NAME}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-spring-app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - C:/Secrets/todo_app/.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

volumes:
  todo-db-data: